apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{APP_NAME}#
  labels:
    app: #{APP_NAME}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{APP_NAME}#
  template:
    metadata:
      labels:
        app: #{APP_NAME}#
    spec:
      containers:
        - name: #{APP_NAME}#
          image: quay.io/keycloak/keycloak:25.0.6
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
          envFrom:
            - secretRef:
                name: secrets-#{APP_NAME}#

          env:
            - name: KC_PROXY
              value: edge
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_URL
              value: #{PROXY}#

          args:
            - start-dev
            #- --hostname
            #- #{PROXY}#