
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-#{APP_NAME}#-1
  namespace: #{NAMESPACE}#
spec:
  vault:
    name: #{KEY_VAULT}# 
    object:
      name: keycloak-db-host
      type: secret 
  output: 
    secret: 
      name: secrets-#{APP_NAME}# 
      dataKey: KC_DB_URL_HOST 


---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-#{APP_NAME}#-2
  namespace: #{NAMESPACE}#
spec:
  vault:
    name: #{KEY_VAULT}# 
    object:
      name: keycloak-db-username 
      type: secret 
  output: 
    secret: 
      name: secrets-#{APP_NAME}# 
      dataKey: KC_DB_USERNAME 


---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-#{APP_NAME}#-3
  namespace: #{NAMESPACE}#
spec:
  vault:
    name: #{KEY_VAULT}# 
    object:
      name: keycloak-db-password
      type: secret 
  output: 
    secret: 
      name: secrets-#{APP_NAME}# 
      dataKey: KC_DB_PASSWORD 


---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-#{APP_NAME}#-4
  namespace: #{NAMESPACE}#
spec:
  vault:
    name: #{KEY_VAULT}# 
    object:
      name: keycloak-db-port
      type: secret 
  output: 
    secret: 
      name: secrets-#{APP_NAME}# 
      dataKey: KC_DB_URL_PORT 


---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-#{APP_NAME}#-5
  namespace: #{NAMESPACE}#
spec:
  vault:
    name: #{KEY_VAULT}# 
    object:
      name: keycloak-db-database 
      type: secret
  output: 
    secret: 
      name: secrets-#{APP_NAME}# 
      dataKey: KC_DB_URL_DATABASE


---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-#{APP_NAME}#-6
  namespace: #{NAMESPACE}#
spec:
  vault:
    name: #{KEY_VAULT}# 
    object:
      name: keycloak-db-schema
      type: secret
  output: 
    secret: 
      name: secrets-#{APP_NAME}# 
      dataKey: KC_DB_SCHEMA

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-#{APP_NAME}#-7
  namespace: #{NAMESPACE}#
spec:
  vault:
    name: #{KEY_VAULT}# 
    object:
      name: keycloak-db-type
      type: secret
  output: 
    secret: 
      name: secrets-#{APP_NAME}# 
      dataKey: KC_DB

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-#{APP_NAME}#-8
  namespace: #{NAMESPACE}#
spec:
  vault:
    name: #{KEY_VAULT}# 
    object:
      name: keycloak-user-admin
      type: secret
  output: 
    secret: 
      name: secrets-#{APP_NAME}# 
      dataKey: KEYCLOAK_ADMIN

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-#{APP_NAME}#-9
  namespace: #{NAMESPACE}#
spec:
  vault:
    name: #{KEY_VAULT}# 
    object:
      name: keycloak-user-admin-password
      type: secret
  output: 
    secret: 
      name: secrets-#{APP_NAME}# 
      dataKey: KEYCLOAK_ADMIN_PASSWORD